import {
  Account,
  Client,
  Disbursement,
  Employee,
  Expense,
  ExpenseCategory,
  JournalEntry,
  Loan,
  LoanProduct,
  Repayment,
  RepaymentScheduleItem,
  User,
} from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 1,
    username: 'admin',
    fullName: 'System Administrator',
    role: 'admin',
    active: true,
    createdAt: '2026-01-01',
    lastLogin: '2026-09-16 08:30',
  },
  {
    id: 2,
    username: 'm_choto',
    fullName: 'Michael Choto',
    role: 'manager',
    active: true,
    createdAt: '2026-01-15',
    lastLogin: '2026-09-15 16:45',
  },
  {
    id: 3,
    username: 's_ndlovu',
    fullName: 'Sarah Ndlovu',
    role: 'loan_officer',
    active: true,
    createdAt: '2026-02-01',
    lastLogin: '2026-09-16 09:12',
  },
  {
    id: 4,
    username: 'd_moyo',
    fullName: 'David Moyo',
    role: 'teller',
    active: true,
    createdAt: '2026-02-10',
    lastLogin: '2026-09-16 10:05',
  },
];

export const INITIAL_ACCOUNTS: Account[] = [
  { id: 1, code: '1000', name: 'Cash and Bank', type: 'Asset', isControl: true },
  { id: 2, code: '1100', name: 'Loans Receivable - Principal', type: 'Asset', isControl: true },
  { id: 3, code: '1150', name: 'Interest Receivable', type: 'Asset', isControl: true },
  { id: 4, code: '2000', name: 'Accounts Payable', type: 'Liability', isControl: false },
  { id: 5, code: '2050', name: 'Client Credit Balances / Unapplied Payments', type: 'Liability', isControl: true },
  { id: 6, code: '2100', name: 'PAYE Payable', type: 'Liability', isControl: true },
  { id: 7, code: '2150', name: 'NSSA Payable', type: 'Liability', isControl: true },
  { id: 8, code: '2160', name: 'AIDS Levy Payable', type: 'Liability', isControl: true },
  { id: 9, code: '3000', name: "Owner's Capital", type: 'Equity', isControl: false },
  { id: 10, code: '3100', name: 'Retained Earnings', type: 'Equity', isControl: false },
  { id: 11, code: '4000', name: 'Interest Income', type: 'Income', isControl: true },
  { id: 12, code: '4100', name: 'Admin Fee Income', type: 'Income', isControl: true },
  { id: 13, code: '4200', name: 'Penalty Fee Income', type: 'Income', isControl: true },
  { id: 14, code: '4300', name: 'Bad Debt Recovery Income', type: 'Income', isControl: true },
  { id: 15, code: '4500', name: 'Rollover Fee Income', type: 'Income', isControl: true },
  { id: 16, code: '5000', name: 'Bad Debts Written Off', type: 'Expense', isControl: true },
  { id: 17, code: '5100', name: 'Salaries and Wages Expense', type: 'Expense', isControl: true },
  { id: 18, code: '5900', name: 'General Operating Expenses', type: 'Expense', isControl: false },
];

export const INITIAL_EXPENSE_CATEGORIES: ExpenseCategory[] = [
  { id: 1, name: 'Rent', description: 'Office branch lease and rentals' },
  { id: 2, name: 'Salaries and Wages', description: 'Staff payroll & commissions' },
  { id: 3, name: 'Utilities', description: 'Electricity, water, solar backup' },
  { id: 4, name: 'Office Supplies', description: 'Stationery, printing, toner' },
  { id: 5, name: 'Transport', description: 'Field visits, client verification fuel' },
  { id: 6, name: 'Communication', description: 'Internet, telephone, SMS alerts' },
  { id: 7, name: 'Bank Charges', description: 'Bank transfer & ledger fees' },
  { id: 8, name: 'Miscellaneous', description: 'Sundry administrative costs' },
];

export const INITIAL_LOCATIONS = [
  'Harare Central',
  'Bulawayo Central',
  'Mutare',
  'Gweru',
  'Chitungwiza',
  'Chinhoyi',
  'Masvingo',
];

export const INITIAL_LOAN_PRODUCTS: LoanProduct[] = [
  {
    id: 1,
    name: 'Standard Monthly Business Loan',
    interestMethod: 'flat',
    interestRate: 10.0,
    ratePeriod: 'month',
    adminFeePct: 2.5,
    penaltyPct: 5.0,
    gracePeriodDays: 3,
    repaymentFrequency: 'monthly',
    termUnitLabel: 'months',
    active: true,
  },
  {
    id: 2,
    name: 'Non-Standard Weekly Micro-Loan (Flat)',
    interestMethod: 'flat',
    interestRate: 15.0,
    ratePeriod: 'loan_term',
    adminFeePct: 2.0,
    penaltyPct: 5.0,
    gracePeriodDays: 2,
    repaymentFrequency: 'weekly',
    termUnitLabel: 'weeks',
    active: true,
  },
  {
    id: 3,
    name: 'Reducing Balance Working Capital',
    interestMethod: 'reducing_balance',
    interestRate: 8.5,
    ratePeriod: 'month',
    adminFeePct: 2.0,
    penaltyPct: 5.0,
    gracePeriodDays: 5,
    repaymentFrequency: 'monthly',
    termUnitLabel: 'months',
    active: true,
  },
  {
    id: 4,
    name: 'Interest-Only Balloon Loan',
    interestMethod: 'interest_only_balloon',
    interestRate: 18.0,
    ratePeriod: 'month',
    adminFeePct: 3.0,
    penaltyPct: 5.0,
    gracePeriodDays: 3,
    repaymentFrequency: 'monthly',
    termUnitLabel: 'months',
    active: true,
  },
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 1,
    clientNo: 'CL-00001',
    firstName: 'Tendai',
    lastName: 'Musarurwa',
    nationalId: '63-198421-F-42',
    gender: 'Male',
    location: 'Harare Central',
    phone: '+263 77 214 8892',
    address: 'Stand 412, Samora Machel Ave, Harare',
    occupation: 'Grocery Wholesaler',
    averageIncome: 3200,
    guarantor: 'Farai Musarurwa',
    guarantorPhone: '+263 77 391 0021',
    dateRegistered: '2026-01-10',
    status: 'Active',
    notes: 'Established wholesale business with stable stock turnover.',
    createdAt: '2026-01-10',
  },
  {
    id: 2,
    clientNo: 'CL-00002',
    firstName: 'Rudo',
    lastName: 'Chikwava',
    nationalId: '08-442190-B-08',
    gender: 'Female',
    location: 'Bulawayo Central',
    phone: '+263 71 498 3312',
    address: 'Shop 14, 8th Avenue Mall, Bulawayo',
    occupation: 'Boutique Apparel Owner',
    averageIncome: 1850,
    guarantor: 'Blessing Chikwava',
    guarantorPhone: '+263 77 820 4410',
    dateRegistered: '2026-01-18',
    status: 'Active',
    notes: 'Reliable payer, repeat applicant.',
    createdAt: '2026-01-18',
  },
  {
    id: 3,
    clientNo: 'CL-00003',
    firstName: 'Kudzai',
    lastName: 'Gumbo',
    nationalId: '47-310892-K-19',
    gender: 'Male',
    location: 'Chitungwiza',
    phone: '+263 77 655 4910',
    address: 'Unit D Extension, Chitungwiza',
    occupation: 'Poultry Farmer',
    averageIncome: 1400,
    guarantor: 'Tariro Gumbo',
    guarantorPhone: '+263 73 319 8440',
    dateRegistered: '2026-02-05',
    status: 'Active',
    notes: '500 bird broiler project with confirmed off-taker agreement.',
    createdAt: '2026-02-05',
  },
  {
    id: 4,
    clientNo: 'CL-00004',
    firstName: 'Nyasha',
    lastName: 'Mutasa',
    nationalId: '12-901244-C-75',
    gender: 'Female',
    location: 'Mutare',
    phone: '+263 78 400 9182',
    address: 'Main Street Produce Market, Mutare',
    occupation: 'Fruit & Vegetable Distributor',
    averageIncome: 950,
    guarantor: 'Edson Mutasa',
    guarantorPhone: '+263 77 109 2384',
    dateRegistered: '2026-02-12',
    status: 'Active',
    notes: 'Operates two market stalls.',
    createdAt: '2026-02-12',
  },
  {
    id: 5,
    clientNo: 'CL-00005',
    firstName: 'Simbarashe',
    lastName: 'Mpofu',
    nationalId: '29-087123-A-29',
    gender: 'Male',
    location: 'Gweru',
    phone: '+263 77 923 1140',
    address: 'Light Industrial Site, Gweru',
    occupation: 'Metal Fabricator & Welder',
    averageIncome: 2100,
    guarantor: 'Vimbai Mpofu',
    guarantorPhone: '+263 71 290 8821',
    dateRegistered: '2026-03-01',
    status: 'Active',
    notes: 'Fabricates window frames and security gates.',
    createdAt: '2026-03-01',
  },
];

export const INITIAL_LOANS: Loan[] = [
  {
    id: 1,
    loanNo: 'LN-00001',
    clientId: 1,
    productId: 1,
    principal: 4000,
    interestRate: 10.0,
    interestMethod: 'flat',
    ratePeriod: 'month',
    termMonths: 4,
    repaymentFrequency: 'monthly',
    applicationDate: '2026-05-01',
    disbursementDate: '2026-05-05',
    firstDueDate: '2026-06-05',
    maturityDate: '2026-09-05',
    adminFee: 100,
    status: 'Active',
    approvalStatus: 'Approved',
    approvedBy: 2,
    approvedAt: '2026-05-03',
    purpose: 'Restocking wholesale fast-moving consumer goods',
    collateral: 'Commercial Delivery Van (Registration ADL-4190)',
    createdAt: '2026-05-01',
  },
  {
    id: 2,
    loanNo: 'LN-00002',
    clientId: 2,
    productId: 2,
    principal: 1200,
    interestRate: 15.0,
    interestMethod: 'flat',
    ratePeriod: 'loan_term',
    termMonths: 6,
    repaymentFrequency: 'weekly',
    applicationDate: '2026-08-01',
    disbursementDate: '2026-08-03',
    firstDueDate: '2026-08-10',
    maturityDate: '2026-09-14',
    adminFee: 24,
    status: 'Active',
    approvalStatus: 'Approved',
    approvedBy: 2,
    approvedAt: '2026-08-02',
    purpose: 'Bulk winter clothing inventory purchase',
    collateral: 'Sewing equipment & store fixtures',
    createdAt: '2026-08-01',
  },
  {
    id: 3,
    loanNo: 'LN-00003',
    clientId: 3,
    productId: 1,
    principal: 2000,
    interestRate: 10.0,
    interestMethod: 'flat',
    ratePeriod: 'month',
    termMonths: 3,
    repaymentFrequency: 'monthly',
    applicationDate: '2026-09-01',
    disbursementDate: undefined,
    firstDueDate: '2026-10-02',
    adminFee: 50,
    status: 'Pending',
    approvalStatus: 'Approved',
    approvedBy: 2,
    approvedAt: '2026-09-03',
    purpose: 'Purchasing 4-week broiler feeds and vaccines',
    collateral: 'Poultry housing & backup generator',
    createdAt: '2026-09-01',
  },
  {
    id: 4,
    loanNo: 'LN-00004',
    clientId: 4,
    productId: 2,
    principal: 800,
    interestRate: 15.0,
    interestMethod: 'flat',
    ratePeriod: 'loan_term',
    termMonths: 4,
    repaymentFrequency: 'weekly',
    applicationDate: '2026-09-10',
    adminFee: 16,
    status: 'Pending',
    approvalStatus: 'Pending',
    purpose: 'Produce inventory restocking ahead of weekend market',
    collateral: 'Personal Guarantor',
    createdAt: '2026-09-10',
  },
  {
    id: 5,
    loanNo: 'LN-00005',
    clientId: 5,
    productId: 1,
    principal: 3000,
    interestRate: 10.0,
    interestMethod: 'flat',
    ratePeriod: 'month',
    termMonths: 3,
    repaymentFrequency: 'monthly',
    applicationDate: '2026-03-01',
    disbursementDate: '2026-03-05',
    firstDueDate: '2026-04-05',
    maturityDate: '2026-06-05',
    adminFee: 75,
    status: 'Closed',
    approvalStatus: 'Approved',
    approvedBy: 2,
    approvedAt: '2026-03-02',
    purpose: 'Purchase of steel profile sheets and inverter welder',
    collateral: 'Workshop machinery',
    createdAt: '2026-03-01',
  },
];

export const INITIAL_SCHEDULES: RepaymentScheduleItem[] = [
  // Loan 1 (4 months @ $1,000 principal + $400 interest = $1,400/mo)
  {
    id: 101,
    loanId: 1,
    installmentNo: 1,
    dueDate: '2026-06-05',
    principalDue: 1000,
    interestDue: 400,
    totalDue: 1400,
    principalPaid: 1000,
    interestPaid: 400,
    penaltyCharged: 0,
    penaltyPaid: 0,
    status: 'Paid',
  },
  {
    id: 102,
    loanId: 1,
    installmentNo: 2,
    dueDate: '2026-07-05',
    principalDue: 1000,
    interestDue: 400,
    totalDue: 1400,
    principalPaid: 1000,
    interestPaid: 400,
    penaltyCharged: 0,
    penaltyPaid: 0,
    status: 'Paid',
  },
  {
    id: 103,
    loanId: 1,
    installmentNo: 3,
    dueDate: '2026-08-05',
    principalDue: 1000,
    interestDue: 400,
    totalDue: 1400,
    principalPaid: 1000,
    interestPaid: 400,
    penaltyCharged: 0,
    penaltyPaid: 0,
    status: 'Paid',
  },
  {
    id: 104,
    loanId: 1,
    installmentNo: 4,
    dueDate: '2026-09-05',
    principalDue: 1000,
    interestDue: 400,
    totalDue: 1400,
    principalPaid: 500,
    interestPaid: 400,
    penaltyCharged: 25,
    penaltyPaid: 0,
    status: 'Overdue',
  },

  // Loan 2 (6 weeks @ $200 principal + $30 interest = $230/wk)
  {
    id: 201,
    loanId: 2,
    installmentNo: 1,
    dueDate: '2026-08-10',
    principalDue: 200,
    interestDue: 30,
    totalDue: 230,
    principalPaid: 200,
    interestPaid: 30,
    penaltyCharged: 0,
    penaltyPaid: 0,
    status: 'Paid',
  },
  {
    id: 202,
    loanId: 2,
    installmentNo: 2,
    dueDate: '2026-08-17',
    principalDue: 200,
    interestDue: 30,
    totalDue: 230,
    principalPaid: 200,
    interestPaid: 30,
    penaltyCharged: 0,
    penaltyPaid: 0,
    status: 'Paid',
  },
  {
    id: 203,
    loanId: 2,
    installmentNo: 3,
    dueDate: '2026-08-24',
    principalDue: 200,
    interestDue: 30,
    totalDue: 230,
    principalPaid: 200,
    interestPaid: 30,
    penaltyCharged: 0,
    penaltyPaid: 0,
    status: 'Paid',
  },
  {
    id: 204,
    loanId: 2,
    installmentNo: 4,
    dueDate: '2026-08-31',
    principalDue: 200,
    interestDue: 30,
    totalDue: 230,
    principalPaid: 200,
    interestPaid: 30,
    penaltyCharged: 0,
    penaltyPaid: 0,
    status: 'Paid',
  },
  {
    id: 205,
    loanId: 2,
    installmentNo: 5,
    dueDate: '2026-09-07',
    principalDue: 200,
    interestDue: 30,
    totalDue: 230,
    principalPaid: 200,
    interestPaid: 30,
    penaltyCharged: 0,
    penaltyPaid: 0,
    status: 'Paid',
  },
  {
    id: 206,
    loanId: 2,
    installmentNo: 6,
    dueDate: '2026-09-14',
    principalDue: 200,
    interestDue: 30,
    totalDue: 230,
    principalPaid: 0,
    interestPaid: 0,
    penaltyCharged: 0,
    penaltyPaid: 0,
    status: 'Pending',
  },

  // Loan 5 (Settled)
  {
    id: 501,
    loanId: 5,
    installmentNo: 1,
    dueDate: '2026-04-05',
    principalDue: 1000,
    interestDue: 300,
    totalDue: 1300,
    principalPaid: 1000,
    interestPaid: 300,
    penaltyCharged: 0,
    penaltyPaid: 0,
    status: 'Paid',
  },
  {
    id: 502,
    loanId: 5,
    installmentNo: 2,
    dueDate: '2026-05-05',
    principalDue: 1000,
    interestDue: 300,
    totalDue: 1300,
    principalPaid: 1000,
    interestPaid: 300,
    penaltyCharged: 0,
    penaltyPaid: 0,
    status: 'Paid',
  },
  {
    id: 503,
    loanId: 5,
    installmentNo: 3,
    dueDate: '2026-06-05',
    principalDue: 1000,
    interestDue: 300,
    totalDue: 1300,
    principalPaid: 1000,
    interestPaid: 300,
    penaltyCharged: 0,
    penaltyPaid: 0,
    status: 'Paid',
  },
];

export const INITIAL_DISBURSEMENTS: Disbursement[] = [
  {
    id: 1,
    loanId: 1,
    amount: 4000,
    disbursementDate: '2026-05-05',
    method: 'Bank Transfer',
    reference: 'FT-260505-01',
    disbursedBy: 1,
    notes: 'Disbursed directly to client bank account',
    createdAt: '2026-05-05',
  },
  {
    id: 2,
    loanId: 2,
    amount: 1200,
    disbursementDate: '2026-08-03',
    method: 'Mobile Money',
    reference: 'MM-8812903',
    disbursedBy: 1,
    notes: 'EcoCash business payout',
    createdAt: '2026-08-03',
  },
  {
    id: 3,
    loanId: 5,
    amount: 3000,
    disbursementDate: '2026-03-05',
    method: 'Cash',
    reference: 'CSH-0305-99',
    disbursedBy: 1,
    notes: 'Cash disbursement counter receipt',
    createdAt: '2026-03-05',
  },
];

export const INITIAL_REPAYMENTS: Repayment[] = [
  {
    id: 1,
    loanId: 1,
    paymentDate: '2026-06-04',
    amount: 1400,
    principalPaid: 1000,
    interestPaid: 400,
    penaltyPaid: 0,
    adminFeePaid: 0,
    method: 'Bank Transfer',
    reference: 'RPY-00101',
    receivedBy: 4,
    notes: 'Month 1 installment',
    createdAt: '2026-06-04',
  },
  {
    id: 2,
    loanId: 1,
    paymentDate: '2026-07-05',
    amount: 1400,
    principalPaid: 1000,
    interestPaid: 400,
    penaltyPaid: 0,
    adminFeePaid: 0,
    method: 'Bank Transfer',
    reference: 'RPY-00102',
    receivedBy: 4,
    notes: 'Month 2 installment',
    createdAt: '2026-07-05',
  },
  {
    id: 3,
    loanId: 1,
    paymentDate: '2026-08-05',
    amount: 1400,
    principalPaid: 1000,
    interestPaid: 400,
    penaltyPaid: 0,
    adminFeePaid: 0,
    method: 'Bank Transfer',
    reference: 'RPY-00103',
    receivedBy: 4,
    notes: 'Month 3 installment',
    createdAt: '2026-08-05',
  },
  {
    id: 4,
    loanId: 1,
    paymentDate: '2026-09-08',
    amount: 900,
    principalPaid: 500,
    interestPaid: 400,
    penaltyPaid: 0,
    adminFeePaid: 0,
    method: 'Bank Transfer',
    reference: 'RPY-00104',
    receivedBy: 4,
    notes: 'Partial payment on final installment ($500 balance remaining)',
    createdAt: '2026-09-08',
  },
  {
    id: 5,
    loanId: 2,
    paymentDate: '2026-08-10',
    amount: 230,
    principalPaid: 200,
    interestPaid: 30,
    penaltyPaid: 0,
    adminFeePaid: 0,
    method: 'Mobile Money',
    reference: 'RPY-00201',
    receivedBy: 4,
    notes: 'Week 1 installment',
    createdAt: '2026-08-10',
  },
  {
    id: 6,
    loanId: 2,
    paymentDate: '2026-08-17',
    amount: 230,
    principalPaid: 200,
    interestPaid: 30,
    penaltyPaid: 0,
    adminFeePaid: 0,
    method: 'Mobile Money',
    reference: 'RPY-00202',
    receivedBy: 4,
    notes: 'Week 2 installment',
    createdAt: '2026-08-17',
  },
  {
    id: 7,
    loanId: 2,
    paymentDate: '2026-08-24',
    amount: 230,
    principalPaid: 200,
    interestPaid: 30,
    penaltyPaid: 0,
    adminFeePaid: 0,
    method: 'Mobile Money',
    reference: 'RPY-00203',
    receivedBy: 4,
    notes: 'Week 3 installment',
    createdAt: '2026-08-24',
  },
  {
    id: 8,
    loanId: 2,
    paymentDate: '2026-08-31',
    amount: 230,
    principalPaid: 200,
    interestPaid: 30,
    penaltyPaid: 0,
    adminFeePaid: 0,
    method: 'Mobile Money',
    reference: 'RPY-00204',
    receivedBy: 4,
    notes: 'Week 4 installment',
    createdAt: '2026-08-31',
  },
  {
    id: 9,
    loanId: 2,
    paymentDate: '2026-09-07',
    amount: 230,
    principalPaid: 200,
    interestPaid: 30,
    penaltyPaid: 0,
    adminFeePaid: 0,
    method: 'Mobile Money',
    reference: 'RPY-00205',
    receivedBy: 4,
    notes: 'Week 5 installment',
    createdAt: '2026-09-07',
  },
  {
    id: 10,
    loanId: 5,
    paymentDate: '2026-06-04',
    amount: 3900,
    principalPaid: 3000,
    interestPaid: 900,
    penaltyPaid: 0,
    adminFeePaid: 0,
    method: 'Cash',
    reference: 'RPY-00501',
    receivedBy: 4,
    notes: 'Full settlement of loan LN-00005',
    createdAt: '2026-06-04',
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 1,
    categoryId: 1,
    expenseDate: '2026-08-01',
    amount: 650,
    paidTo: 'Commercial Properties Trust',
    description: 'Harare Head Office Rent - August',
    reference: 'EXP-2608-01',
    recordedBy: 1,
    createdAt: '2026-08-01',
  },
  {
    id: 2,
    categoryId: 3,
    expenseDate: '2026-08-10',
    amount: 140,
    paidTo: 'ZESA Power Distribution',
    description: 'Monthly office electricity tokens',
    reference: 'EXP-2608-02',
    recordedBy: 1,
    createdAt: '2026-08-10',
  },
  {
    id: 3,
    categoryId: 5,
    expenseDate: '2026-08-18',
    amount: 120,
    paidTo: 'TotalEnergies Samora Machel',
    description: 'Fuel for field verification visits',
    reference: 'EXP-2608-03',
    recordedBy: 3,
    createdAt: '2026-08-18',
  },
  {
    id: 4,
    categoryId: 6,
    expenseDate: '2026-09-01',
    amount: 180,
    paidTo: 'Liquid Home Zimbabwe',
    description: 'Fibre broadband internet connection',
    reference: 'EXP-2609-01',
    recordedBy: 1,
    createdAt: '2026-09-01',
  },
];

export const INITIAL_JOURNAL_ENTRIES: JournalEntry[] = [
  // Initial Capital injection
  {
    id: 1,
    entryDate: '2026-01-01',
    reference: 'CAP-0001',
    sourceType: 'manual',
    description: 'Initial Owner Capital Injection',
    location: 'Harare Central',
    createdBy: 1,
    createdAt: '2026-01-01',
    lines: [
      { id: 1, journalEntryId: 1, accountId: 1, debit: 25000, credit: 0, memo: 'Capital deposit into bank' },
      { id: 2, journalEntryId: 1, accountId: 9, debit: 0, credit: 25000, memo: 'Initial equity contribution' },
    ],
  },
  // Disbursement LN-00001 ($4,000)
  {
    id: 2,
    entryDate: '2026-05-05',
    reference: 'DISB-00001',
    sourceType: 'disbursement',
    sourceId: 1,
    description: 'Disbursement of loan LN-00001 to Tendai Musarurwa',
    location: 'Harare Central',
    createdBy: 1,
    createdAt: '2026-05-05',
    lines: [
      { id: 3, journalEntryId: 2, accountId: 2, debit: 4000, credit: 0, memo: 'Loan principal asset booked' },
      { id: 4, journalEntryId: 2, accountId: 1, debit: 0, credit: 4000, memo: 'Cash disbursed' },
    ],
  },
  // Admin fee LN-00001 ($100)
  {
    id: 3,
    entryDate: '2026-05-05',
    reference: 'FEE-00001',
    sourceType: 'fee',
    sourceId: 1,
    description: 'Admin fee earned on loan LN-00001',
    location: 'Harare Central',
    createdBy: 1,
    createdAt: '2026-05-05',
    lines: [
      { id: 5, journalEntryId: 3, accountId: 1, debit: 100, credit: 0, memo: 'Admin fee collected' },
      { id: 6, journalEntryId: 3, accountId: 12, debit: 0, credit: 100, memo: 'Admin fee income' },
    ],
  },
  // Repayments for LN-00001 ($3,500 principal, $1,600 interest)
  {
    id: 4,
    entryDate: '2026-09-08',
    reference: 'RPY-BATCH-01',
    sourceType: 'repayment',
    sourceId: 1,
    description: 'Total collections received on loan LN-00001',
    location: 'Harare Central',
    createdBy: 4,
    createdAt: '2026-09-08',
    lines: [
      { id: 7, journalEntryId: 4, accountId: 1, debit: 5100, credit: 0, memo: 'Cash received from client' },
      { id: 8, journalEntryId: 4, accountId: 2, debit: 0, credit: 3500, memo: 'Principal reduced' },
      { id: 9, journalEntryId: 4, accountId: 11, debit: 0, credit: 1600, memo: 'Interest income recognized' },
    ],
  },
  // Expenses batch
  {
    id: 5,
    entryDate: '2026-09-01',
    reference: 'EXP-BATCH-01',
    sourceType: 'expense',
    description: 'Operating Expenses recorded through September',
    location: 'Harare Central',
    createdBy: 1,
    createdAt: '2026-09-01',
    lines: [
      { id: 10, journalEntryId: 5, accountId: 18, debit: 1090, credit: 0, memo: 'Operating expenses incurred' },
      { id: 11, journalEntryId: 5, accountId: 1, debit: 0, credit: 1090, memo: 'Cash paid out' },
    ],
  },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 1,
    employeeNo: 'EMP-001',
    firstName: 'Tawanda',
    lastName: 'Marufu',
    nationalId: '63-200984-P-12',
    jobTitle: 'Senior Credit Officer',
    department: 'Credit & Risk',
    dateHired: '2025-06-01',
    basicSalary: 1200,
    bankName: 'Stanbic Bank',
    bankAccountNo: '9140003182910',
    nssaNumber: 'NSSA-881920',
    taxNumber: 'TIN-491028',
    active: true,
  },
  {
    id: 2,
    employeeNo: 'EMP-002',
    firstName: 'Grace',
    lastName: 'Chigwada',
    nationalId: '08-192844-G-40',
    jobTitle: 'Accountant & Cashier',
    department: 'Finance',
    dateHired: '2025-08-15',
    basicSalary: 950,
    bankName: 'CABS',
    bankAccountNo: '1004928172',
    nssaNumber: 'NSSA-902184',
    taxNumber: 'TIN-771829',
    active: true,
  },
  {
    id: 3,
    employeeNo: 'EMP-003',
    firstName: 'Peter',
    lastName: 'Sibanda',
    nationalId: '15-449102-L-04',
    jobTitle: 'Field Verification Officer',
    department: 'Operations',
    dateHired: '2026-01-10',
    basicSalary: 750,
    bankName: 'Nedbank',
    bankAccountNo: '11990284711',
    nssaNumber: 'NSSA-655419',
    taxNumber: 'TIN-339182',
    active: true,
  },
];
